name: Test workflow
### Test
on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: |
          echo "github.event.pull_request.head.sha=${{ github.event.pull_request.head.sha }}"
          echo "github.sha=${{ github.sha }}"
          echo "github.event.commits[0].id=${{ github.event.commits[0].id }}"
          echo "github.event.commits=${{ github.event.commits }}"
          echo "github.event.pull_request.commits[0].id=${{ github.event.pull_request.commits[0].id }}"
          echo "github.event.pull_request.commits[-1].id=${{ github.event.pull_request.commits[-1].id }}"
      - name: GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: GITHUB_COMMITS
        env:
          GITHUB_COMMITS: ${{ toJSON(github.event.commits) }}
        run: |
          echo "$GITHUB_COMMITS"
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
        # Don't work:
        # github.event.pull_request.head.ref
        # github.event.pull_request._links.html.href
        # github.event.pull_request.head.sha
        # github.sha
          name: test-build-${{ github.sha }}
          path: README.md
          retention-days: 2

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Debug
        run: |
          echo "github.event.pull_request.head.sha=${{ github.event.pull_request.head.sha }}"
          echo "github.sha=${{ github.sha }}"
          echo "github.event.commits[0].id=${{ github.event.commits[0].id }}"
          echo "github.event.commits[-1].id=${{ github.event.commits[-1].id }}"
          echo "github.event.commits[-2].id=${{ github.event.commits[-2].id }}"
      - name: GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: GITHUB_COMMITS
        env:
          GITHUB_COMMITS: ${{ toJSON(github.event.commits) }}
        run: |
          echo "$GITHUB_COMMITS"
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: test-build-${{ github.event.commits[-2].id }}
          path: /tmp
      - name: Publish a git tag
        run: "cat /tmp/README.md"

